name: Build Spring Boot JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Jar
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    # Paso 2: Configurar JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # Paso 3: Construir el artefacto JAR (saltando tests)
    - name: Package application
      run: mvn clean package -DskipTests

    # Paso 4: Subir el artefacto JAR a GitHub
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/*.jar